---
title: "Mock TLFs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Mock TLFs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE, message=FALSE}
library(gtreg)
library(tidyverse)
```

# Overview

Mock TLFs can be generated by 

1. Creating dummy data.

2. Passing the dummy data to your function of choice.

3. Overwrite the statistic(s) shown to a fixed character string.

# Example `tbl_ae()` TLF

## Dummy data

```{r}
dat_ae <-
  tibble::tibble(
    soc = "System Organ Class 1",
    ae = "AE1",
     grade = factor(1, levels = 1:5)
  ) %>%
  {dplyr::bind_rows(., .)} %>%
  dplyr::mutate(
    id = 1:2,
    strata = c("Arm A", "Arm B")
  )
```

```{r}
dat_ae
```


## TLF

```{r}
dat_ae  %>%
  tbl_ae(
    id = id,
    ae = ae, 
    soc = soc,
    by = grade, 
    strata = strata, 
    statistic = "xx (xx.x)",
     zero_symbol = NULL
  ) %>%
  modify_spanning_header(all_ae_cols() ~ "**{strata} (N=xx), n (%)**") %>%
  modify_caption("**Incidence and Number of AEs by Maximum Grade (N, %)**") %>%
  bold_labels()
```

# Example `tbl_reg_summary()` TLF

## Dummy data

```{r}
dat_reg <-
  df_patient_characteristics |> 
  select(trt, marker, status)
```

```{r}
head(dat_reg)
```


## TLF

```{r, error=TRUE}
dat_reg |> 
  tbl_reg_summary(
    by = trt,
    statistic = list(
      #marker = "xx (xx.x)",
      status = "x (x.x%)"
      )
  ) |> 
  bold_labels()
```

